### PR TITLE
Resolve issue with KMS logging alarms

### PR DESCRIPTION
**Pull request by crissupb**
Update default Lambda version for new deployments.
Set alarm sns topic to a valid topic.
Add alarms for Lambda failures
Issues https://github.com/18F/identity-devops/issues/3008

### After merge update identity-devops PR https://github.com/18F/identity-devops/pull/3011 with new sha

### CODE REVIEW

**Comment by crissupb** [comment]
TF Plan fragment for crissupb environment
```
# module.kms_logging.aws_cloudwatch_metric_alarm.cloudtrail_lambda_backlog will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "cloudtrail_lambda_backlog" {
        actions_enabled           = true
      ~ alarm_actions             = [
          - "arn:aws:sns:us-west-2:894947205914:crissupb-kms-logging-events",
          + "arn:aws:sns:us-west-2:894947205914:slack-otherevents",
        ]
        alarm_description         = "Kinesis backlog for crissupb-cloudtrail-kms"
        alarm_name                = "crissupb-cloudtrail-kms-backlog"
        arn                       = "arn:aws:cloudwatch:us-west-2:894947205914:alarm:crissupb-cloudtrail-kms-backlog"
        comparison_operator       = "GreaterThanOrEqualToThreshold"
        datapoints_to_alarm       = 0
        dimensions                = {
            "QueueName" = "crissupb-kms-ct-events"
        }
        evaluation_periods        = 1
        id                        = "crissupb-cloudtrail-kms-backlog"
        insufficient_data_actions = []
        metric_name               = "ApproximateNumberOfMessagesVisible"
        namespace                 = "AWS/SQS"
        ok_actions                = []
        period                    = 180
        statistic                 = "Maximum"
        tags                      = {}
        threshold                 = 10000
        treat_missing_data        = "ignore"
    }

  # module.kms_logging.aws_cloudwatch_metric_alarm.cloudwatch_lambda_backlog will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "cloudwatch_lambda_backlog" {
        actions_enabled           = true
      ~ alarm_actions             = [
          - "arn:aws:sns:us-west-2:894947205914:crissupb-kms-logging-events",
          + "arn:aws:sns:us-west-2:894947205914:slack-otherevents",
        ]
        alarm_description         = "Kinesis backlog for crissupb-cloudwatch-kms"
        alarm_name                = "crissupb-cloudwatch-kms-backlog"
        arn                       = "arn:aws:cloudwatch:us-west-2:894947205914:alarm:crissupb-cloudwatch-kms-backlog"
        comparison_operator       = "GreaterThanOrEqualToThreshold"
        datapoints_to_alarm       = 0
        dimensions                = {
            "FunctionName" = "crissupb-cloudwatch-kms"
        }
        evaluation_periods        = 1
        id                        = "crissupb-cloudwatch-kms-backlog"
        insufficient_data_actions = []
        metric_name               = "IteratorAge"
        namespace                 = "AWS/Lambda"
        ok_actions                = []
        period                    = 180
        statistic                 = "Maximum"
        tags                      = {}
        threshold                 = 3600000
        treat_missing_data        = "ignore"
    }


```

**Comment by crissupb** [comment]
TF Plan in crissupb for new Lambda alarms
```
# module.kms_logging.module.ct-processor-github-alerts.aws_cloudwatch_metric_alarm.lambda_error_rate[0] will be created
  + resource "aws_cloudwatch_metric_alarm" "lambda_error_rate" {
      + actions_enabled                       = true
      + alarm_actions                         = [
          + "arn:aws:sns:us-west-2:894947205914:slack-otherevents",
        ]
      + alarm_description                     = "Lambda error rate has exceeded 5%"
      + alarm_name                            = "Lambda error rate: crissupb-cloudtrail-kms"
      + arn                                   = (known after apply)
      + comparison_operator                   = "GreaterThanOrEqualToThreshold"
      + datapoints_to_alarm                   = 5
      + evaluate_low_sample_count_percentiles = (known after apply)
      + evaluation_periods                    = 1
      + id                                    = (known after apply)
      + threshold                             = 5
      + treat_missing_data                    = "missing"

      + metric_query {
          + id          = "errors"
          + return_data = false

          + metric {
              + dimensions  = {
                  + "FunctionName" = "crissupb-cloudtrail-kms"
                }
              + metric_name = "Errors"
              + namespace   = "AWS/Lambda"
              + period      = 60
              + stat        = "Sum"
            }
        }
      + metric_query {
          + id          = "invocations"
          + return_data = false

          + metric {
              + dimensions  = {
                  + "FunctionName" = "crissupb-cloudtrail-kms"
                }
              + metric_name = "Invocations"
              + namespace   = "AWS/Lambda"
              + period      = 60
              + stat        = "Sum"
            }
        }
      + metric_query {
          + expression  = "errors / invocations * 100"
          + id          = "error_rate"
          + label       = "Error Rate"
          + return_data = true
        }
    }

  # module.kms_logging.module.cw-processor-github-alerts.aws_cloudwatch_metric_alarm.lambda_error_rate[0] will be created
  + resource "aws_cloudwatch_metric_alarm" "lambda_error_rate" {
      + actions_enabled                       = true
      + alarm_actions                         = [
          + "arn:aws:sns:us-west-2:894947205914:slack-otherevents",
        ]
      + alarm_description                     = "Lambda error rate has exceeded 5%"
      + alarm_name                            = "Lambda error rate: crissupb-cloudwatch-kms"
      + arn                                   = (known after apply)
      + comparison_operator                   = "GreaterThanOrEqualToThreshold"
      + datapoints_to_alarm                   = 5
      + evaluate_low_sample_count_percentiles = (known after apply)
      + evaluation_periods                    = 1
      + id                                    = (known after apply)
      + threshold                             = 5
      + treat_missing_data                    = "missing"

      + metric_query {
          + id          = "errors"
          + return_data = false

          + metric {
              + dimensions  = {
                  + "FunctionName" = "crissupb-cloudwatch-kms"
                }
              + metric_name = "Errors"
              + namespace   = "AWS/Lambda"
              + period      = 60
              + stat        = "Sum"
            }
        }
      + metric_query {
          + id          = "invocations"
          + return_data = false

          + metric {
              + dimensions  = {
                  + "FunctionName" = "crissupb-cloudwatch-kms"
                }
              + metric_name = "Invocations"
              + namespace   = "AWS/Lambda"
              + period      = 60
              + stat        = "Sum"
            }
        }
      + metric_query {
          + expression  = "errors / invocations * 100"
          + id          = "error_rate"
          + label       = "Error Rate"
          + return_data = true
        }
    }

```

**Review by pauldoomgov — COMMENTED** [review]
LGTM

**Review by pauldoomgov — APPROVED** [review]
LGTM

**Pull request merged**
